using ProductManagementSystem.Currencies;
using Xunit;

namespace ProductManagementSystem.EntityFrameworkCore.Applications.Currencies;

public class EfCoreCurrenciesAppServiceTests : CurrenciesAppServiceTests<ProductManagementSystemEntityFrameworkCoreTestModule>
{
}