using ProductManagementSystem.EntityFrameworkCore;
using Xunit;

namespace ProductManagementSystem.EntityFrameworkCore;

public class ProductManagementSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<ProductManagementSystemEntityFrameworkCoreFixture>
{

}
