using Volo.Abp;

namespace ProductManagementSystem.EntityFrameworkCore;

public abstract class ProductManagementSystemEntityFrameworkCoreTestBase : ProductManagementSystemTestBase<ProductManagementSystemEntityFrameworkCoreTestModule>
{

}
