using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ProductManagementSystem.Currencies
{
    public class CurrencyManager : CurrencyManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CurrencyManager(ICurrencyRepository currencyRepository)
            : base(currencyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}